server:
  port: 8099

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defureka:         #tells about the Eureka server details and its refresh time
defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: track-service


  data:
    mongodb:
      repositories:
        enabled: true

      host: localhost


driverClassName: com.mongodb.jdbc.MongoDriver


logging:
  level:
    com.stackroute.route: DEBUG